### ISSUE TITLE
[TEALIUM SWIFT BUG]: App freeze & crash in TealiumTagManagement

### ISSUE THREAD

**Issue by JuhaO81** [Tealium/tealium-swift#148]
**Your Environment**
iOS Version(s) [e.g. 12.1]: Seen on iOS 13 
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 11.6
Swift version [e.g. 4.2]: 5
Tealium Swift library version [e.g. 1.6.7]: 1.9.5
Dependency manager [None/Carthage/CocoaPods]: Carthage
Dependency manager version: -

**Describe the bug**
Application freezes and then crashes bit later. This happens at app launch or app open.

At first this started to happen with Tealium obj-c library that was using WKWebView. This was not really major blocker for us since it was only happening with our pilot release when it had TestFlight feedback feature enabled. Removing either Tealium lib or feedback feature this issue was gone. Both seemed to use WKWebView.

Now this issue started to happen in our production application as well. We are now using Tealium Swift lib 1.9.5. 

**Does a workaround exist?**
We removed TealiumTagManagement framework for now but this means we also lost some of the features we want to have.

**To Reproduce**
Steps
- Open app

Another steps
- At some use cases we perform actions in another app. App switch back to our app freezes the app at some times.

Not easy and not everytime. We can provide some videos & logs & call stacks showcasing this issue. Can I have email address to sent this info to? 

Seems like this is a timing related issue. Is TealiumTagManagement running something on UI thread at app start that causes the freeze and I believe after some time iOS kills the frozen app. 

Crashed: com.apple.main-thread
SIGABRT ABORT 0x000000019b2d3858

0  libsystem_kernel.dylib         0x19b2d3858 __abort_with_payload + 8
1  libsystem_kernel.dylib         0x19b2d7ed8 <redacted> + 104
2  libsystem_kernel.dylib         0x19b2d7e70 abort_with_reason + 30
3  libobjc.A.dylib                0x19b2203f0 <redacted> + 108
4  libobjc.A.dylib                0x19b220384 <redacted> + 30
5  libobjc.A.dylib                0x19b21c544 <redacted> + 318
6  libobjc.A.dylib                0x19b21e350 objc_initWeak + 296
7  libswiftCore.dylib             0x1a9012d30 swift_unknownObjectWeakInit + 60
8  TealiumTagManagement           0x1024b87e4 TealiumTagManagementWKWebView.evaluateJavascript(_:_:) + 229 (TealiumTagManagementWKWebView.swift:229)
9  TealiumTagManagement           0x1024b972c protocol witness for TealiumTagManagementProtocol.evaluateJavascript(_:_:) in conformance TealiumTagManagementWKWebView + 20 (<compiler-generated>:20)
10 TealiumTagManagement           0x1024a9da8 closure #1 in TealiumTagManagementModule.enableNotifications() + 111 (TealiumTagManagementModule.swift:111)
11 TealiumTagManagement           0x1024a9e80 thunk for @escaping @callee_guaranteed (@in_guaranteed Notification) -> () + 112 (<compiler-generated>:112)
12 Foundation                     0x19b8c83a0 <redacted> + 48
13 Foundation                     0x19b8ce004 <redacted> + 24
14 Foundation                     0x19b7d05a4 <redacted> + 104
15 Foundation                     0x19b8d0344 <redacted> + 24
16 Foundation                     0x19b7d027c <redacted> + 752
17 Foundation                     0x19b8d0d70 <redacted> + 24
18 Foundation                     0x19b8d0830 <redacted> + 184
19 libdispatch.dylib              0x19b18e134 <redacted> + 32
20 libdispatch.dylib              0x19b18f5ac <redacted> + 20
21 libdispatch.dylib              0x19b19b7d4 _dispatch_main_queue_callback_4CF + 832
22 CoreFoundation                 0x19b4688d4 <redacted> + 16
23 CoreFoundation                 0x19b46358c <redacted> + 1692
24 CoreFoundation                 0x19b462bc8 CFRunLoopRunSpecific + 480
25 GraphicsServices               0x1a58445cc GSEventRunModal + 164
26 UIKitCore                      0x19f615744 UIApplicationMain + 1936
27 NBHouseholdFI                  0x1003cece4 main + 15 (main.m:15)
28 libdyld.dylib                  0x19b2df384 <redacted> + 4

**Additional context**

**Comment by craigrouse** [comment]
@JuhaO81 Sorry you're experiencing this issue. Firstly, I'd advise upgrading to 1.9.6, since we did fix a webview-related crash in that release, but I don't expect that fix to solve your specific issue. It's worth upgrading anyway.

Please send the details to support@tealium.com and we'll be glad to take a look for you. I'd say if it was happening in both the ObjC and Swift libraries, then there's a chance there could be some JS loading via the webview that's causing a deadlock in some circumstances - this is just an educated guess at this point. Our support team can take a look at the profile that's being loaded and verify if this might be the case.

Look forward to receiving the info from you. I work closely with the support team, and I'll let them know to expect a ticket from you 🙂

**Comment by JuhaO81** [comment]
Info sent to support. At some point I also tested older obj-c lib using only UIWebView and that did not have this issue so might relate to WKWebView also.

**Comment by christinasund** [comment]
Hi @JuhaO81 We just released a patch for this ([1.9.7](https://github.com/Tealium/tealium-swift/releases/tag/1.9.7)] as well as a brand new major version with many new features and improvements if you would like to give it a try: [2.0.0](https://github.com/Tealium/tealium-swift/releases/tag/2.0.0) We made sure to include the fix in this version as well 🙂 Whichever version you choose, let us know if this solves the problem you were seeing. Thanks!

**Comment by JuhaO81** [comment]
Thx updating our next release with 1.9.7 and will look into 2.0 for upcoming releases

**Comment by JuhaO81** [comment]
1.9.7 Still had same issue and we updated to 2.0. Need to wait for our next release to reach customers to verify if this issue is gone.

**Comment by craigrouse** [comment]
@JuhaO81 Just circling back on this since it's been a while. Did you release the new version of your app yet with v2 of the SDK, and has it eliminated the crash? Thanks.

**Comment by craigrouse** [comment]
@JuhaO81 any updates on this one? No rush from our end - just checking back in as we still have an open ticket for it. Thanks.

**Comment by craigrouse** [comment]
Closing for now due to inactivity; please let us know if we should reopen it.
