### ISSUE TITLE
[TEALIUM SWIFT BUG]: Cookies aren't populated in WKWebViews when using Tealium 

### ISSUE THREAD

**Issue by alongGH** [Tealium/tealium-swift#159]
**Your Environment**
iOS Version(s) [e.g. 12.1]: 12-14
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 11.5, 12
Swift version [e.g. 4.2]: 5
Tealium Swift library version [e.g. 1.6.7]: 2.1.1
Dependency manager [None/Carthage/CocoaPods]: Cocoapods
Dependency manager version:  1.7.5

**Describe the bug**
When using version 5.6.5 of the tealium-ios library, we were seeing an issue where cookies that were present in the native WKHTTPCookieStore weren’t being populated into the Cookie header of URL requests being loaded in our own WKWebViews.  This defect was only present when loading the Tealium library. We usually observed the defect when loading the first webview in our app, or after returning to the app after a period of inactivity and attempting to load a webview.   We tried various workarounds from within our code, like manually creating the Cookie header based on the contents of WKHTTPCookieStore, but we weren’t able to find a solution that fixed the missing cookies issue while  also not introducing other defects.

We then attempted to switch to the latest version of the tealium-swift library, but we encountered the same issue with missing cookies in outgoing requests in WKWebView.

**Does a workaround exist?**
We then attempted to switch to the latest version of the tealium-swift library, but we encountered the same issue with missing cookies in outgoing requests in WKWebView.

 Because tealium-swift is distributed through source, we were able to do a little more troubleshooting , and one potential workaround was updating tealium-swift’s TagManagementWKWebView.setupWebview() method to use a non-persistent WKWebsiteDataStore instead of the default, shared one. 

**To Reproduce**
1. Enable tealium
2. Create a WKWebView and load an URL
3. Observe missing cookies in outgoing requests.

**Expected behavior**
Cookies that are in the WKHTTPCookieStore should be populated in the request

**Comment by christinasund** [comment]
@alongGH Thanks for bringing this to us! We will take a look and get back soon.

**Comment by craigrouse** [comment]
@alongGH Thanks for the detailed writeup and suggestions. Cookies with WKWebView are pretty tricky to get right, as we found when migrating from UIWebView.

It wouldn't make sense for us to switch to a nonPersistent cookie store by default, since in most cases, analytics tags implemented through the webview require the use of cookies to store an anonymous visitor ID, otherwise they will show 100% of app users as new visitors. 

There is something else you can try that may help, however. When we migrated over from UIWebView, I found an issue where cookies never persisted, which was resolved by creating an empty cookie store observer and registering it using `WKWebsiteDataStore.default().httpCookieStore`

If you add this code to your own webview, perhaps it might be enough to fix the issue. It's a long shot, but worth a try I think. Here's the snippet:

```
class MyWebView{...
            // required to force cookies to sync
            if #available(iOS 11, *) {
                WKWebsiteDataStore.default().httpCookieStore.add(self)
            }
}
```
```
@available(iOS 11.0, *)
extension MyWebView: WKHTTPCookieStoreObserver {

    /// Listens for cookie changes in WKHTTPCookieStore
    ///￼  NOTE: this exists purely to work around an issue where cookies are not properly synced to WKWebView instances
    ///
    /// - Parameter cookieStore: `WKHTTPCookieStore` instance
    func cookiesDidChange(in cookieStore: WKHTTPCookieStore) {
        DispatchQueue.main.async {
            cookieStore.getAllCookies { _ in
                // no action necessary; retrieving the cookies forces them to sync
            }
        }
    }
}

```

Discussed further on this thread: https://developer.apple.com/forums/thread/97194

Perhaps you've already tried this? Let us know how you get on, and if it doesn't work, we'll do our best to find an alternative solution for you.

**Comment by craigrouse** [comment]
One thing to add, this issue is a problem for the Cordova project too, which uses webviews to render the entire app, and they have a dedicated plugin to fix the issue, which injects a cookie into the WKWebView as soon as the app launches. It might be worth trying this for your webview:

https://github.com/CWBudde/cordova-plugin-wkwebview-inject-cookie/blob/master/src/ios/WKWebViewInjectCookie.m

This may also be a solution we can add to our library, and remove the cookie store observer workaround, which I suspect may be causing this issue when multiple webviews are in play.

**Comment by alongGH** [comment]
@craigrouse Thanks for the response and suggestions.

I tried adding the WKHTTPCookieStoreObserver to our WKWebViews, but I'm still seeing the same issue.

We manually sync cookies to the NSHTTPCookieStorage before launching the WkWebView, similar to the Cordova fix, but we don't see them in the outgoing HTTP request with Tealium enabled.

**Comment by craigrouse** [comment]
@alongGH Just to let you know we're looking into this still and hopefully we'll be able to find a solution. We'll keep you updated.

**Comment by craigrouse** [comment]
@alongGH We've been unable to reproduce this. I've uploaded our test project here: https://github.com/craigrouse/wkwebview-cookies

It would be great if you could take a look at the test project and see if that aligns with what you're doing in your own app. We've tried lots of variations:

* Starting Tealium at launch, then loading the webview
* Loading the webview, then starting Tealium
* Both of the above options with and without setting a custom cookie in `WKWebsiteDataStore`

In all cases, our cookies are preserved as expected. If this doesn't help, we'd be happy to arrange a screenshare with you to take a look at the issue in your app.

**Comment by alongGH** [comment]
@craigrouse We haven't been able to reproduce the problem in the sample project yet.  Could you arrange a screenshare session for next week?

**Comment by craigrouse** [comment]
@alongGH absolutely. Could I ask you to send a message to support@tealium.com and let us know the Tealium account and profile you're using? We can then get a screenshare arranged. Thank you.

**Comment by alongGH** [comment]
Thanks for meeting with us.

Based on the suggestions, I tried double-checking that we were always setting cookies on the main thread.  There were a few instances where we were setting cookies on a global priority queue;  I changed those instances to run on the main thread, but I was still seeing the error.

Removing the override URLs didn't have any effect.

Disabling the tagmanagement module by removing it from the dispatchers array did clear the error.

**Comment by craigrouse** [comment]
@alongGH Thanks for the feedback. I will liaise with the support team regarding next steps, so expect to hear back shortly.

**Comment by craigrouse** [comment]
Closing this bug, as a workaround was found. After extensive investigation, we found that if there are 2 webviews in an app, cookies don't always behave as expected. Specifically, session cookies with no explicit expiry may not persist. The workaround was to change the session cookies to be persistent cookies with a short validity period. A bug report has been filed with Apple.
